version: '3.1'

services:
  web:
    image: nginx:1.14
    working_dir: /app
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - app

  app:
    build:
      context: .
      dockerfile: app.dockerfile 
    working_dir: /app
    expose:
      - 9000
    volumes:
      - ./app:/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - database
      - redis

  redis:
    image: redis:5.0
    expose:
      - 6379

  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
  
  adminer:
    image: adminer
    ports:
      - 8083:8080

  pgadmin:
    image: dpage/pgadmin4
    links:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: develop@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8084:80

